/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BookRouteImport } from './routes/_book'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BookIndexRouteImport } from './routes/_book.index'
import { Route as BookCvRouteImport } from './routes/_book.cv'
import { Route as BookGalleryRouteImport } from './routes/_book.gallery'
import { Route as BookProjectsRouteImport } from './routes/_book.projects'
import { Route as BookWatchingRouteImport } from './routes/_book.watching'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as MediaSplatRouteImport } from './routes/media.$'
import { Route as BookBlogIndexRouteImport } from './routes/_book.blog.index'
import { Route as BookBlogSlugRouteImport } from './routes/_book.blog.$slug'
import { Route as AdminPostsIdRouteImport } from './routes/admin.posts.$id'
import { Route as AdminPostsNewRouteImport } from './routes/admin.posts.new'
import { Route as ApiRpcSplatRouteImport } from './routes/api.rpc.$'
import { Route as ApiAdminRpcSplatRouteImport } from './routes/api.admin.rpc.$'

const BookRoute = BookRouteImport.update({
  id: '/_book',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BookIndexRoute = BookIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BookRoute,
} as any)
const BookCvRoute = BookCvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => BookRoute,
} as any)
const BookGalleryRoute = BookGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => BookRoute,
} as any)
const BookProjectsRoute = BookProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => BookRoute,
} as any)
const BookWatchingRoute = BookWatchingRouteImport.update({
  id: '/watching',
  path: '/watching',
  getParentRoute: () => BookRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const MediaSplatRoute = MediaSplatRouteImport.update({
  id: '/media/$',
  path: '/media/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BookBlogIndexRoute = BookBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => BookRoute,
} as any)
const BookBlogSlugRoute = BookBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => BookRoute,
} as any)
const AdminPostsIdRoute = AdminPostsIdRouteImport.update({
  id: '/posts/$id',
  path: '/posts/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsNewRoute = AdminPostsNewRouteImport.update({
  id: '/posts/new',
  path: '/posts/new',
  getParentRoute: () => AdminRoute,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminRpcSplatRoute = ApiAdminRpcSplatRouteImport.update({
  id: '/api/admin/rpc/$',
  path: '/api/admin/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof BookIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cv': typeof BookCvRoute
  '/gallery': typeof BookGalleryRoute
  '/projects': typeof BookProjectsRoute
  '/watching': typeof BookWatchingRoute
  '/media/$': typeof MediaSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/$slug': typeof BookBlogSlugRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/blog/': typeof BookBlogIndexRoute
  '/api/admin/rpc/$': typeof ApiAdminRpcSplatRoute
}
export interface FileRoutesByTo {
  '/cv': typeof BookCvRoute
  '/gallery': typeof BookGalleryRoute
  '/projects': typeof BookProjectsRoute
  '/watching': typeof BookWatchingRoute
  '/media/$': typeof MediaSplatRoute
  '/': typeof BookIndexRoute
  '/admin': typeof AdminIndexRoute
  '/blog/$slug': typeof BookBlogSlugRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/blog': typeof BookBlogIndexRoute
  '/api/admin/rpc/$': typeof ApiAdminRpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_book': typeof BookRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/_book/cv': typeof BookCvRoute
  '/_book/gallery': typeof BookGalleryRoute
  '/_book/projects': typeof BookProjectsRoute
  '/_book/watching': typeof BookWatchingRoute
  '/media/$': typeof MediaSplatRoute
  '/_book/': typeof BookIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_book/blog/$slug': typeof BookBlogSlugRoute
  '/admin/posts/$id': typeof AdminPostsIdRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/_book/blog/': typeof BookBlogIndexRoute
  '/api/admin/rpc/$': typeof ApiAdminRpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cv'
    | '/gallery'
    | '/projects'
    | '/watching'
    | '/media/$'
    | '/admin/'
    | '/blog/$slug'
    | '/admin/posts/$id'
    | '/admin/posts/new'
    | '/api/rpc/$'
    | '/blog/'
    | '/api/admin/rpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/cv'
    | '/gallery'
    | '/projects'
    | '/watching'
    | '/media/$'
    | '/'
    | '/admin'
    | '/blog/$slug'
    | '/admin/posts/$id'
    | '/admin/posts/new'
    | '/api/rpc/$'
    | '/blog'
    | '/api/admin/rpc/$'
  id:
    | '__root__'
    | '/_book'
    | '/admin'
    | '/_book/cv'
    | '/_book/gallery'
    | '/_book/projects'
    | '/_book/watching'
    | '/media/$'
    | '/_book/'
    | '/admin/'
    | '/_book/blog/$slug'
    | '/admin/posts/$id'
    | '/admin/posts/new'
    | '/api/rpc/$'
    | '/_book/blog/'
    | '/api/admin/rpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  BookRoute: typeof BookRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  MediaSplatRoute: typeof MediaSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
  ApiAdminRpcSplatRoute: typeof ApiAdminRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_book': {
      id: '/_book'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_book/': {
      id: '/_book/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof BookIndexRouteImport
      parentRoute: typeof BookRoute
    }
    '/_book/cv': {
      id: '/_book/cv'
      path: '/cv'
      fullPath: '/cv'
      preLoaderRoute: typeof BookCvRouteImport
      parentRoute: typeof BookRoute
    }
    '/_book/gallery': {
      id: '/_book/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof BookGalleryRouteImport
      parentRoute: typeof BookRoute
    }
    '/_book/projects': {
      id: '/_book/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof BookProjectsRouteImport
      parentRoute: typeof BookRoute
    }
    '/_book/watching': {
      id: '/_book/watching'
      path: '/watching'
      fullPath: '/watching'
      preLoaderRoute: typeof BookWatchingRouteImport
      parentRoute: typeof BookRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/media/$': {
      id: '/media/$'
      path: '/media/$'
      fullPath: '/media/$'
      preLoaderRoute: typeof MediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_book/blog/': {
      id: '/_book/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BookBlogIndexRouteImport
      parentRoute: typeof BookRoute
    }
    '/_book/blog/$slug': {
      id: '/_book/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BookBlogSlugRouteImport
      parentRoute: typeof BookRoute
    }
    '/admin/posts/$id': {
      id: '/admin/posts/$id'
      path: '/posts/$id'
      fullPath: '/admin/posts/$id'
      preLoaderRoute: typeof AdminPostsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts/new': {
      id: '/admin/posts/new'
      path: '/posts/new'
      fullPath: '/admin/posts/new'
      preLoaderRoute: typeof AdminPostsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/rpc/$': {
      id: '/api/admin/rpc/$'
      path: '/api/admin/rpc/$'
      fullPath: '/api/admin/rpc/$'
      preLoaderRoute: typeof ApiAdminRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BookRouteChildren {
  BookCvRoute: typeof BookCvRoute
  BookGalleryRoute: typeof BookGalleryRoute
  BookProjectsRoute: typeof BookProjectsRoute
  BookWatchingRoute: typeof BookWatchingRoute
  BookIndexRoute: typeof BookIndexRoute
  BookBlogSlugRoute: typeof BookBlogSlugRoute
  BookBlogIndexRoute: typeof BookBlogIndexRoute
}

const BookRouteChildren: BookRouteChildren = {
  BookCvRoute: BookCvRoute,
  BookGalleryRoute: BookGalleryRoute,
  BookProjectsRoute: BookProjectsRoute,
  BookWatchingRoute: BookWatchingRoute,
  BookIndexRoute: BookIndexRoute,
  BookBlogSlugRoute: BookBlogSlugRoute,
  BookBlogIndexRoute: BookBlogIndexRoute,
}

const BookRouteWithChildren = BookRoute._addFileChildren(BookRouteChildren)

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminPostsIdRoute: typeof AdminPostsIdRoute
  AdminPostsNewRoute: typeof AdminPostsNewRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminPostsIdRoute: AdminPostsIdRoute,
  AdminPostsNewRoute: AdminPostsNewRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  BookRoute: BookRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  MediaSplatRoute: MediaSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
  ApiAdminRpcSplatRoute: ApiAdminRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
